// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// UsersGet implements GET /users operation.
//
// Optional extended description in CommonMark or HTML.
//
// GET /users
func (UnimplementedHandler) UsersGet(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// Optional extended description in CommonMark or HTML.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdGet implements GET /users/{userId} operation.
//
// Optional extended description in CommonMark or HTML.
//
// GET /users/{userId}
func (UnimplementedHandler) UsersUserIdGet(ctx context.Context, params UsersUserIdGetParams) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
