// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	BuyPostOperation          OperationName = "BuyPost"
	MarketsAmountGetOperation OperationName = "MarketsAmountGet"
	MarketsGetOperation       OperationName = "MarketsGet"
	SellPostOperation         OperationName = "SellPost"
	UpdateUserIdGetOperation  OperationName = "UpdateUserIdGet"
	UsersGetOperation         OperationName = "UsersGet"
	UsersPostOperation        OperationName = "UsersPost"
	UsersUserIdGetOperation   OperationName = "UsersUserIdGet"
	UsersUserIdPostOperation  OperationName = "UsersUserIdPost"
)
